/* eslint-disable @typescript-eslint/no-unsafe-assignment */
/* eslint-disable @typescript-eslint/no-unsafe-call */
import { api } from "@/utils/api";
import { type reporting } from "@prisma/client";
import { useSession } from "next-auth/react";
import Head from "next/head";

import { Table, Badge } from "@mantine/core";

const Index = () => {
  const list = api.report.getAll.useQuery();

  const { data: session, status } = useSession();
  if (status !== "authenticated") {
    return null;
  }

  if (session?.user.role !== "user") {
    return null;
  }

  const jobColors: Record<string, string> = {
    review: "blue",
    progress: "pink",
    complete: "cyan",
  };
  function listingReport({ report }: { report: reporting }) {
    return (
      <>
        <Table.Tr key={report.id}>
          <Table.Td>{report.title}</Table.Td>
          <Table.Td>{report.type}</Table.Td>
          <Table.Td>{report.userId}</Table.Td>
          <Table.Td>{report.createdAt.toLocaleString()}</Table.Td>
          <Table.Td>{report.description}</Table.Td>
          <Table.Td>
            <Badge
              color={jobColors[report.status_report.toLowerCase()]}
              variant="light"
            >
              {report.status_report.toLowerCase()}
            </Badge>
          </Table.Td>
        </Table.Tr>
      </>
    );
  }

  return (
    <>
      <Head>
        <title>Report</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h2 className="item-center justify-center">
        table for {session.user.email}
      </h2>
      <div className=" m-auto flex w-full items-center justify-center">
        <Table>
          <Table.Thead>
            <Table.Tr>
              <Table.Th>Report Title</Table.Th>
              <Table.Th>Type Crash</Table.Th>
              <Table.Th>User Id</Table.Th>
              <Table.Th>Created At</Table.Th>
              <Table.Th>Description</Table.Th>
              <Table.Th>Status</Table.Th>
            </Table.Tr>
          </Table.Thead>
          <Table.Tbody>
            {list.data?.map((report) => {
              return listingReport({ report });
            })}
          </Table.Tbody>
        </Table>
      </div>
    </>
  );
};

export default Index;
